### ISSUE TITLE
Getting issues while using products.Get service

### ISSUE THREAD

**Issue by kushthedude** [r0busta/go-shopify-graphql#11]
```
		_ = graphqlclient.NewClient("{hidden}", graphqlclient.WithToken("{hidden}"), graphqlclient.WithVersion("2023-07"))
		gClient := shopifyGraphql.NewClientWithToken("{hidden}", "{hidden}")

		// If no more products, exit the loop
		if len(prods) == 0 {
			break
		}
		opt = pagination.NextPageOptions

		// Print all fetched products
		for _, product := range prods {
			resp, err = gClient.Product.Get(context.Background(), strconv.Itoa(int(product.ID)))
			log.Fatalf("%v", err)
```

I am trying to fetch details of the product via graphQL but stuck at 
```
level=fatal msg="query: Variable $id of type ID! was provided invalid value"
```

**Comment by kushthedude** [comment]
@r0busta Anything which may seem obviously wrong to you?

**Comment by r0busta** [comment]
In Shopify's graphql API, an ID is always a string. Either in format `gid://shopify/{object_name}/{id}` (https://shopify.dev/docs/api/usage/gids) or an base64 encoded version of it.

It seems that you are trying to convert the ID string into int and then back to string here `strconv.Itoa(int(product.ID))`

Where is this variable `product` coming from? Do you get your products from the REST API or somewhere else?

**Comment by kushthedude** [comment]
Thanks a lot @r0busta, I replace ID with adminGraphQLAPIID which gets returned from rest.
I am really new to all this graphql queries & interface. If you don't I would really ask for one last help, I am using this interface to get onlineShopURL which REST doesn't return, I tried product.Get but the query cost exceeded over there, is there a way I can only get onlineShopURL for a given productID? Thanks for your help, I really appreciate this library in golang or else we were really thinking to use Python 😮‍💨

**Comment by r0busta** [comment]
For your use case, something like this should be a good solution:

```go
package main

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/r0busta/go-shopify-graphql-model/v3/graph/model"
)

func main() {
	client := clientWithToken()

	query := `query ($id: ID!) {
			product(id: $id){
				onlineStoreUrl
			}
		}`
	vars := map[string]interface{}{
		"id": "gid://shopify/Product/123",
	}
	out := struct {
		Product *model.Product
	}{}
	err := client.GraphQLClient().QueryString(context.Background(), query, vars, &out)
	if err != nil {
		panic(err)
	}
	
	tmp, _ := json.MarshalIndent(out, "", "    ")
	fmt.Println(string(tmp))

	fmt.Println("OnlineStoreURL: %s", *out.Product.OnlineStoreURL)
}
```

Such a simple query won't exceed the query cost, and it's flexible enough for the case when you want to read more fields not present in the response from the REST API.

**Comment by kushthedude** [comment]
Thanks a lot @r0busta , I will close this issue & ramp up on Shopify GraphQL interface, thanks again.
