### ISSUE TITLE
Challenges working with products

### ISSUE THREAD

**Issue by leighstillard** [r0busta/go-shopify-graphql#7]
Hi there,

I've been trying to get a product going using your library. Thanks for building it and putting it out here on github!

I'm getting this failure on almost any operation that I do:
```bash

[leigh@host shopify-updater-v1m]$ go run .
panic: get bulk query result URL: Bulk operation didn't complete, status=FAILED, error_code=ACCESS_DENIED

goroutine 1 [running]:
main.main()
        /home/primax/workspace/shopify/shopify-updater-v1m/main.go:16 +0x156
exit status 2
[leigh@host shopify-updater-v1m]$
```

I've validated that my client works with other operations such as pulling from collections. My scopes look right. The token has been tested with other tools and it works.

Here is the code I'm using:
```go

package main

import (
	"fmt"

	shopify "github.com/r0busta/go-shopify-graphql/v6"
)

func main() {
	// Create client
	client := shopify.NewClientWithToken("shpat_xxxx", "my-dev-store-1")

	// Get all collections
	products, err := client.Product.ListAll()
	if err != nil {
		panic(err)
	}

	// Print out the result
	for _, p := range products {
		fmt.Println(p.Variants.Edges[0].Node.Title)
	}

}
```

I've also attempted using Product.List("query") using queries I've tested using graphiql, same error. 

Could you please point out what I'm doing wrong? I've looked into the bulk operations go file but I'm not sure if I should be using that at all.

Thanks!

Leigh

Edit: I forgot to mention, I'm authenticating via token as I was never able to get authing with NewClient to work.

**Comment by r0busta** [comment]
Hi Leigh,

Thanks for creating the issue.

I was able to reproduce the error you were getting. It's happening because of the `client.Product` service using, unfortunately, hard-coded queries that query variants for each product. The variants sub-query also includes inventory fields, which require the `read_inventory` access scope.

BTW, I'm curious why the default client didn't work for you. Did you set the env vars as follows?

```
STORE_API_KEY=<private_app_api_key>
STORE_PASSWORD=<private_app_access_token>
STORE_NAME=<store_name>
```

**Comment by r0busta** [comment]
So if you wouldn't like to use extra scopes in your app, I suggest using the `client.BulkOperation.BulkQuery` method for listing all products, as it allows for defining custom GraphQL queries without inventory fields.

Unfortunately, these pre-backed services (`Product`, `Collection`, etc.) use greedy queries to satisfy most cases and hence depend on too many access scopes being granted.

**Comment by leighstillard** [comment]
Thanks r0busta, I'll give that a go.

I tried a whole bunch of ways to use the stated code example for logging in. I used env vars, I hardcoded secret strings, but in the end I couldn't figure it out. Digging into the code I found the token function so have been using that successfully since.

I'd love to share the code but its got hardcoded secrets now. Could it be another scopes issue with my using least privilege scopes?

**Comment by leighstillard** [comment]
Could you possibly give me a tiny example of the inputs for ```client.BulkOperation.BulkQuery```? I'm trying to figure it out working backwards through the code but I'm afraid I might not be proficient enough.

As far as I can tell it's unmarshalling the data structure and then populating it into the query, but yeah this is a bit beyond me without a basic example. 

If you can provide something (preferably for product :)) I'm happy to write it up into more detailed docs in this repo. 

Thanks!

**Comment by leighstillard** [comment]
I just found the example in the examples folder for the above. Please disregard the request for now while I figure this out

**Comment by r0busta** [comment]
Yeah, so I'd say that if you keep getting a `Bulk operation didn't complete, status=FAILED, error_code=ACCESS_DENIED` error, it's most certainly an issue of getting correct scopes. I'd resolve it by gradually building up the query from the simplest, e.g., `products{id}` up to the one your application needs and testing it. At some point, the query should result in an error, and that should point out the required scope.

I hope that helps and I'm looking forward to hearing from you again.

**Comment by leighstillard** [comment]
Thanks yes it did. I broadened my scopes and everything is working well now!

I'm hoping to grow into the bulk queries but for now I'm getting some very overdue pricing updates done. 

Thank you so much for your work on the library.

**Comment by r0busta** [comment]
So does `client.Product.ListAll()` work for you now?

**Comment by leighstillard** [comment]
I'm using client.Product.List("query") as I'm working with over 25,000 products and that will likely grow to over a million soon. I attempted ListAll but I think I very quickly ran out of query credits. I'll go back to that branch and see if I can find what the error was.

**Comment by r0busta** [comment]
Great to hear that it's resolved.

Honestly, I shouldn't have added `client.Product.ListAll()` in the first place. It is a convenient function for quickly hacking together some tools and not for production usage. So I'd say you are already on the right track 😊
